max_epochs: 8
model_type: libert # bert or libert
random_init: 2

data: lr rl dl ld dr rd # relative to nlp_architect/models/li_bert/data/preprocessed_conll
splits: [1, 2, 3]
seeds: [12, 57, 89]
version_tag: # optional: name this experiment version

baseline_str: libert_random_init
baseline_version: version_baseline


li_layer: #5
li_layers: #[2]
all_layers: true
relation: ""
parse_probs: true
replace_final: false
duplicated_rels: false
transpose: false

do_train: true
do_predict: true

num_workers: 88
gpus: 1

overwrite_cache: false # if false, loads features from cached file (faster)
cache_dir: # default: nlp-architect/nlp_architect/cache
output_dir: # default: nlp-architect/nlp_architect/cache/li-bert-models
labels: labels.txt # relative to nlp_architect/models/li_bert/data

model_name_or_path: bert-base-uncased
train_batch_size: 16
eval_batch_size: 16
max_seq_length: 64
adam_epsilon: 1.0e-08
fast_dev_run: false
accumulate_grad_batches: 1
learning_rate: 5.0e-05
gradient_clip_val: 1.0
n_tpu_cores: 0
resume_from_checkpoint: null
tokenizer_name: null
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
logger: true